{% set name = "commitizen" %}
{% set version = "2.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 676094c2aa485630ca8bff16be356a43043fa5dc3310f85a4f2764cf14c40f3d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cz = commitizen.cli:main
    - git-cz = commitizen.cli:main

requirements:
  host:
    - python >=3.6
    - poetry
    - pip
  run:
    - python >=3.6
    - questionary <2.0.0,>=1.4.0
    - decli <0.6.0,>=0.5.2
    - colorama <0.5.0,>=0.4.1
    - termcolor <2.0,>=1.1
    - packaging <22,>=19
    - tomlkit <1.0.0,>=0.5.3
    - jinja2 >=2.10.3
    - pyyaml >=3.08
    - argcomplete <2.0.0,>=1.12.1
    - typing-extensions
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - typing_extensions <5.0.0,>=4.0.1
    # - chardet <6.0.0,>=5.0.0

test:
  imports:
    - commitizen
  commands:
    - cz
    - git-cz

about:
  home: https://github.com/commitizen-tools/commitizen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to define a standard way of committing
  dev_url: https://github.com/commitizen-tools/commitizen

extra:
  recipe-maintainers:
    - cpcloud
