{% set name = "commitizen" %}
{% set version = "4.6.3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/commitizen-{{ version }}.tar.gz
  sha256: c97d48a49d84bea27496737e43fdea5ccc87e1e2d288b0a071bf97292548ffd9

build:
  entry_points:
    - cz = commitizen.cli:main
    - git-cz = commitizen.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - questionary >=2.0,<3.0
    - decli >=0.6.0,<1.0
    - colorama >=0.4.1,<1.0
    - termcolor >=1.1,<3
    - packaging >=19
    - tomlkit >=0.5.3,<1.0.0
    - jinja2 >=2.10.3
    - pyyaml >=3.08
    - argcomplete >=1.12.1,<3.7
    - typing_extensions >=4.0.1,<5.0.0  # [py<311]
    - charset-normalizer >=2.1.0,<4
    - importlib-metadata >=8.0.0,<9  # [py<310]

test:
  imports:
    - commitizen
  commands:
    - pip check
    - cz --help
    - git-cz --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/commitizen-tools/commitizen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to define a standard way of committing
  dev_url: https://github.com/commitizen-tools/commitizen

extra:
  recipe-maintainers:
    - kmnhan
    - cpcloud
