{% set name = "commitizen" %}
{% set version = "4.6.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/commitizen-{{ version }}.tar.gz
  sha256: cc1c9f8937e59a7c54321443aa49dd246e07b829e305c7cbff1d7f7e32e449fe

build:
  entry_points:
    - cz = commitizen.cli:main
    - git-cz = commitizen.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - questionary <3.0,>=2.0
    - decli <1.0,>=0.6.0
    - colorama <1.0,>=0.4.1
    - termcolor <3,>=1.1
    - packaging >=19
    - tomlkit <1.0.0,>=0.5.3
    - jinja2 >=2.10.3
    - pyyaml >=3.08
    - argcomplete <3.6,>=1.12.1
    - typing_extensions <5.0.0,>=4.0.1
    - charset-normalizer <4,>=2.1.0
    - importlib-metadata >=8.0.0,<9
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0

test:
  imports:
    - commitizen
  commands:
    - pip check
    - cz --help
    - git-cz --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/commitizen-tools/commitizen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to define a standard way of committing
  dev_url: https://github.com/commitizen-tools/commitizen

extra:
  recipe-maintainers:
    - kmnhan
    - cpcloud
