{% set name = "commitizen" %}
{% set version = "4.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/commitizen-{{ version }}.tar.gz
  sha256: 718a5a2a1be7c8fb1fecd3cb8da57b22fb6a2f54b7897e4d69d3adacf9c3bdeb

build:
  entry_points:
    - cz = commitizen.cli:main
    - git-cz = commitizen.cli:main
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - questionary <3.0,>=2.0
    - prompt_toolkit !=3.0.52
    - decli <1.0,>=0.6.0
    - colorama <1.0,>=0.4.1
    - termcolor <4.0.0,>=1.1.0
    - packaging >=19
    - tomlkit <1.0.0,>=0.8.0
    - jinja2 >=2.10.3
    - pyyaml >=3.8
    - argcomplete <3.7,>=1.12.1
    - typing_extensions <5.0.0,>=4.0.1
    - charset-normalizer <4,>=2.1.0
    - deprecated <2,>=1.2.13
    - importlib-metadata <8.7.0,>=8.0.0
    # - prompt-toolkit !=3.0.52

test:
  imports:
    - commitizen
  commands:
    - pip check
    - cz --help
    - git-cz --help
  requires:
    - python
    - pip

about:
  home: https://github.com/commitizen-tools/commitizen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to define a standard way of committing
  dev_url: https://github.com/commitizen-tools/commitizen

extra:
  recipe-maintainers:
    - kmnhan
    - cpcloud
