{% set name = "commitizen" %}
{% set version = "4.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/commitizen-{{ version }}.tar.gz
  sha256: ef95f2ef354b438dce7c6164e5d47d10cc377df666ee65a116bcfcb146bb0c0a

build:
  entry_points:
    - cz = commitizen.cli:main
    - git-cz = commitizen.cli:main
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - questionary <3.0,>=2.0
    - decli <1.0,>=0.6.0
    - colorama <1.0,>=0.4.1
    - termcolor <3,>=1.1
    - packaging >=19
    - tomlkit <1.0.0,>=0.5.3
    - jinja2 >=2.10.3
    - pyyaml >=3.08
    - argcomplete <3.7,>=1.12.1
    - typing_extensions <5.0.0,>=4.0.1
    - charset-normalizer <4,>=2.1.0
    - importlib-metadata >=8.0.0,<9  # [py<310]
    # - importlib_metadata <9,>=8.0.0

test:
  imports:
    - commitizen
  commands:
    - pip check
    - cz --help
    - git-cz --help
  requires:
    - python
    - pip

about:
  home: https://github.com/commitizen-tools/commitizen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to define a standard way of committing
  dev_url: https://github.com/commitizen-tools/commitizen

extra:
  recipe-maintainers:
    - kmnhan
    - cpcloud
