{% set name = "commitizen" %}
{% set version = "3.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/commitizen-{{ version }}.tar.gz
  sha256: 6ab973e91d07c1e745c6c0efe6dd0708b1f6d8fd7e4ab5e7c773b5ceb3df4ff0

build:
  entry_points:
    - cz = commitizen.cli:main
    - git-cz = commitizen.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - questionary <3.0,>=2.0
    - decli <0.7.0,>=0.6.0
    - colorama <0.5.0,>=0.4.1
    - termcolor <3,>=1.1
    - packaging >=19
    - tomlkit <1.0.0,>=0.5.3
    - jinja2 >=2.10.3
    - pyyaml >=3.08
    - argcomplete <3.6,>=1.12.1
    - typing_extensions <5.0.0,>=4.0.1
    - charset-normalizer <4,>=2.1.0
    - importlib-metadata >=8.0.0,<9
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0
    # - importlib_metadata <9,>=8.0.0

test:
  imports:
    - commitizen
  commands:
    - pip check
    - cz --help
    - git-cz --help
  requires:
    - pip

about:
  home: https://github.com/commitizen-tools/commitizen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to define a standard way of committing
  dev_url: https://github.com/commitizen-tools/commitizen

extra:
  recipe-maintainers:
    - kmnhan
    - cpcloud
