schema_version: 1

context:
  name: commitizen
  version: 4.6.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/commitizen-${{ version }}.tar.gz
  sha256: c97d48a49d84bea27496737e43fdea5ccc87e1e2d288b0a071bf97292548ffd9

build:
  number: 2
  skip: match(python, "<3.9")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - cz = commitizen.cli:main
      - git-cz = commitizen.cli:main

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - questionary >=2.0,<3.0
    - decli >=0.6.0,<1.0
    - colorama >=0.4.1,<1.0
    - termcolor >=1.1,<3
    - packaging >=19
    - tomlkit >=0.5.3,<1.0.0
    - jinja2 >=2.10.3
    - pyyaml >=3.08
    - argcomplete >=1.12.1,<3.7
    - if: match(python, "<3.11")
      then: typing_extensions >=4.0.1,<5.0.0
    - charset-normalizer >=2.1.0,<4
    - if: match(python, "<3.10")
      then: importlib-metadata >=8.0.0,<9

tests:
  - python:
      imports:
        - commitizen
      pip_check: true
  - requirements:
      run:
        - python
        - pip
    script:
      - cz --help
      - git-cz --help

about:
  license: MIT
  license_file: LICENSE
  summary: Tool to define a standard way of committing
  homepage: https://github.com/commitizen-tools/commitizen
  repository: https://github.com/commitizen-tools/commitizen

extra:
  recipe-maintainers:
    - kmnhan
    - cpcloud
